### DISCUSSION TITLE
How can I reference "/config" in the configuration?

### DISCUSSION THREAD

**Discussion by andarotajo** [frenck/action-home-assistant#78] [Q&A] [answered]
Hey I've recently managed to set up this action and I'm loving it so far :) There is one issue I can't manage to resolve though. So my configuration has the following parts:

```yaml
homeassistant:
  allowlist_external_dirs:
    - "/config/logs/"

sensor:
  - platform: file
    name: Core Config Validity
    file_path: "/config/logs/core-config-check.json"
    value_template: >-
      {% if "\"ok\"" in value %}
        valid
      {% elif "\"error\"" in value %}
        invalid
      {% else %}
        unavailable
      {% endif %}
````

Since the action works in the repositories workspace on the runner, this directory can not be found. I tried adding steps to create the "/config/logs" directory which works but the check still throws an error that this directory doesn't exist

I also tried using `./logs` instead of `/config/logs` which worked with the action but for some reason my Home Assistant (OS) can't handle that one because it logs me

`'./logs/core-config-check.json' is not an allowed directory`

Has anyone encountered a similar problem? I'm running out of ideas here :/
